//! Android uygulama hedef kataloglarını tek yerde tutar.
#[derive(Debug, Clone, Copy)]
/// Android uygulama hedef kataloğundaki tek paket kaydını temsil eder.
pub(super) struct AndroidAppTarget {
    pub(super) platform: &'static str,
    pub(super) package: &'static str,
    pub(super) category: &'static str,
    pub(super) priority: &'static str,
    pub(super) storage_hint: &'static str,
}

pub(super) const ANDROID_APP_TARGETS: &[AndroidAppTarget] = &[
    AndroidAppTarget {
        platform: "Google Mail",
        package: "com.google.android.gm",
        category: "account_mail",
        priority: "global_high",
        storage_hint: "Google hesap izleri AccountManager, Gmail uygulama paketi ve bildirimlerde aranır.",
    },
    AndroidAppTarget {
        platform: "Google Play Services",
        package: "com.google.android.gms",
        category: "account_identity",
        priority: "global_high",
        storage_hint: "Google kimlik ve servis varlığı için temel paket; private veri root gerektirir.",
    },
    AndroidAppTarget {
        platform: "Instagram",
        package: "com.instagram.android",
        category: "social",
        priority: "global_high",
        storage_hint: "Paylaşımlı Pictures/Movies Instagram klasörleri ve AccountManager/notification izleri kontrol edilir.",
    },
    AndroidAppTarget {
        platform: "X / Twitter",
        package: "com.twitter.android",
        category: "social",
        priority: "global_high",
        storage_hint: "Oturum verisi private storage tarafındadır; non-root süreç, bildirim ve app media izleri alınır.",
    },
    AndroidAppTarget {
        platform: "Facebook",
        package: "com.facebook.katana",
        category: "social",
        priority: "global_high",
        storage_hint: "Oturum/cache private storage tarafındadır; non-root paket, süreç ve bildirim izi raporlanır.",
    },
    AndroidAppTarget {
        platform: "Messenger",
        package: "com.facebook.orca",
        category: "messaging",
        priority: "global_high",
        storage_hint: "Mesaj içeriği private storage tarafındadır; medya ve bildirim izleri kontrol edilir.",
    },
    AndroidAppTarget {
        platform: "WhatsApp",
        package: "com.whatsapp",
        category: "messaging",
        priority: "global_high",
        storage_hint: "Android/media ve eski WhatsApp/Media klasörleri non-root için en değerli kaynaklardır.",
    },
    AndroidAppTarget {
        platform: "WhatsApp Business",
        package: "com.whatsapp.w4b",
        category: "messaging",
        priority: "global_high",
        storage_hint: "Business medya klasörü ve bildirim izleri non-root toplanabilir; chat DB root/yedek gerektirir.",
    },
    AndroidAppTarget {
        platform: "Telegram",
        package: "org.telegram.messenger",
        category: "messaging",
        priority: "global_high",
        storage_hint: "Telegram/ ve Android/media dizinleri medya için kontrol edilir; private cache root gerektirir.",
    },
    AndroidAppTarget {
        platform: "Signal",
        package: "org.thoughtcrime.securesms",
        category: "messaging",
        priority: "global_medium",
        storage_hint: "Şifreli mesaj verisi private storage tarafındadır; non-root sadece varlık ve sınırlı medya izi verir.",
    },
    AndroidAppTarget {
        platform: "TikTok",
        package: "com.zhiliaoapp.musically",
        category: "social_video",
        priority: "global_high",
        storage_hint: "Paylaşımlı medya, indirme ve bildirim izleri kontrol edilir; oturum private storage tarafındadır.",
    },
    AndroidAppTarget {
        platform: "BiP",
        package: "com.turkcell.bip",
        category: "messaging_tr",
        priority: "turkey_high",
        storage_hint: "Türkiye'de yaygın mesajlaşma uygulaması; medya klasörü ve bildirim izleri kontrol edilir.",
    },
    AndroidAppTarget {
        platform: "Trendyol",
        package: "trendyol.com",
        category: "shopping_tr",
        priority: "turkey_high",
        storage_hint: "Sipariş/oturum verisi private storage tarafındadır; non-root paket, bildirim ve app storage izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "Hepsiburada",
        package: "com.pozitron.hepsiburada",
        category: "shopping_tr",
        priority: "turkey_high",
        storage_hint: "Alışveriş oturumu private storage tarafındadır; non-root bildirim, usage ve app storage izleri alınır.",
    },
    AndroidAppTarget {
        platform: "Sahibinden",
        package: "com.sahibinden",
        category: "classifieds_tr",
        priority: "turkey_high",
        storage_hint: "İlan/arama/mesajlaşma izleri private storage tarafında olabilir; non-root dış depolama ve bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "Getir",
        package: "com.getir",
        category: "delivery_tr",
        priority: "turkey_high",
        storage_hint: "Konum/sipariş oturumu private storage tarafındadır; non-root paket, bildirim ve usage izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "Yemeksepeti / foodpanda",
        package: "com.global.foodpanda.android",
        category: "food_delivery_tr",
        priority: "turkey_high",
        storage_hint: "Sipariş/konum verisi private storage tarafındadır; non-root uygulama varlığı ve bildirim izleri alınır.",
    },
    AndroidAppTarget {
        platform: "Yemeksepeti Legacy",
        package: "com.yemeksepeti.yemeksepeti",
        category: "food_delivery_tr",
        priority: "turkey_medium",
        storage_hint: "Eski paket adı olasılığı için tutulur; varsa aynı depolama yolları kontrol edilir.",
    },
    AndroidAppTarget {
        platform: "Migros",
        package: "com.inomera.sm",
        category: "grocery_tr",
        priority: "turkey_high",
        storage_hint: "Market/yemek/üyelik akışı private storage tarafındadır; non-root bildirim ve app storage izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "e-Nabız",
        package: "tr.gov.saglik.enabiz",
        category: "health_tr",
        priority: "turkey_high",
        storage_hint: "Sağlık verisi hassastır ve private storage/root/yasal izin gerektirir; non-root sadece varlık/iz raporu üretir.",
    },
    AndroidAppTarget {
        platform: "Papara",
        package: "com.mobillium.papara",
        category: "finance_wallet_tr",
        priority: "turkey_high",
        storage_hint: "Elektronik para/finans oturumu private storage tarafındadır; non-root sadece paket, usage ve bildirim izi verir.",
    },
    AndroidAppTarget {
        platform: "Ziraat Mobil",
        package: "com.ziraat.ziraatmobil",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "Banka verisi private storage tarafındadır; non-root sadece paket, usage ve bildirim metaverisi raporlanır.",
    },
    AndroidAppTarget {
        platform: "Garanti BBVA",
        package: "com.garanti.cepsubesi",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "Banka uygulaması private storage kullanır; iç veri erişimi root/yasal yetki gerektirir.",
    },
    AndroidAppTarget {
        platform: "İşCep",
        package: "com.pozitron.iscep",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "İş Bankası mobil bankacılık verisi private storage tarafındadır; non-root paket, usage ve bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "Akbank Mobil",
        package: "com.akbank.android.apps.akbank_direkt",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "Akbank mobil bankacılık oturumu private storage tarafındadır; non-root sadece paket/usage/bildirim izi verir.",
    },
    AndroidAppTarget {
        platform: "Yapı Kredi Mobil",
        package: "com.ykb.android",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "Yapı Kredi mobil bankacılık verisi private storage tarafındadır; non-root kullanım ve bildirim izleri kontrol edilir.",
    },
    AndroidAppTarget {
        platform: "VakıfBank Mobil",
        package: "com.vakifbank.mobile",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "VakıfBank mobil bankacılık verisi private storage tarafındadır; non-root paket/usage/bildirim izi verir.",
    },
    AndroidAppTarget {
        platform: "Halkbank Mobil",
        package: "com.tmobtech.halkbank",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "Halkbank mobil bankacılık verisi private storage tarafındadır; non-root kullanım ve bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "QNB Mobil",
        package: "com.finansbank.mobile.cepsube",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "QNB mobil bankacılık verisi private storage tarafındadır; non-root paket, usage ve bildirim metaverisi raporlanır.",
    },
    AndroidAppTarget {
        platform: "MobilDeniz",
        package: "com.denizbank.mobildeniz",
        category: "banking_tr",
        priority: "turkey_high",
        storage_hint: "DenizBank mobil bankacılık verisi private storage tarafındadır; non-root kullanım ve bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "Kuveyt Türk Mobil",
        package: "com.kuveytturk.mobil",
        category: "banking_tr",
        priority: "turkey_medium",
        storage_hint: "Kuveyt Türk mobil bankacılık verisi private storage tarafındadır; non-root paket/usage/bildirim izi verir.",
    },
    AndroidAppTarget {
        platform: "ING Mobil",
        package: "com.ingbanktr.ingmobil",
        category: "banking_tr",
        priority: "turkey_medium",
        storage_hint: "ING mobil bankacılık verisi private storage tarafındadır; non-root kullanım ve bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "CEPTETEB",
        package: "com.teb",
        category: "banking_tr",
        priority: "turkey_medium",
        storage_hint: "TEB mobil bankacılık verisi private storage tarafındadır; non-root paket/usage/bildirim izi verir.",
    },
    AndroidAppTarget {
        platform: "HSBC Turkey",
        package: "tr.com.hsbc.hsbcturkey",
        category: "banking_tr",
        priority: "turkey_medium",
        storage_hint: "HSBC Turkey mobil bankacılık verisi private storage tarafındadır; non-root kullanım ve bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "Turkish Airlines",
        package: "com.turkishairlines.mobile",
        category: "travel_tr",
        priority: "turkey_medium",
        storage_hint: "Bilet/hesap bilgileri private storage tarafındadır; non-root dosya ve bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "Pegasus",
        package: "com.pozitron.pegasus",
        category: "travel_tr",
        priority: "turkey_medium",
        storage_hint: "Seyahat hesabı private storage tarafındadır; non-root kullanım ve bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "BiTaksi",
        package: "com.bitaksi.musteri",
        category: "transport_tr",
        priority: "turkey_medium",
        storage_hint: "Konum/seyahat geçmişi private storage tarafındadır; non-root app storage ve bildirim izleri kontrol edilir.",
    },
    AndroidAppTarget {
        platform: "Martı",
        package: "com.martitech.marti",
        category: "transport_tr",
        priority: "turkey_medium",
        storage_hint: "Konum ve sürüş oturumu private storage tarafındadır; non-root paket/usage/bildirim izleri alınır.",
    },
    AndroidAppTarget {
        platform: "Discord",
        package: "com.discord",
        category: "messaging",
        priority: "global_medium",
        storage_hint: "Oturum ve mesaj cache private storage tarafındadır; non-root süreç/bildirim izleri raporlanır.",
    },
    AndroidAppTarget {
        platform: "LinkedIn",
        package: "com.linkedin.android",
        category: "social_business",
        priority: "global_medium",
        storage_hint: "Oturum private storage tarafındadır; non-root paket, süreç ve bildirim izleri raporlanır.",
    },
];
